export const readqurandata = [
  {
    number: '01',
    title: 'Al-Fatiha',
    info: 'The Openar',
    arabic: 'الفاتحة',
    count: '7 verses',
  },
  {
    number: '02',
    title: 'Al-Baqarah',
    info: 'The Cow',
    arabic: 'البقرة',
    count: '286 verses',
  },
  {
    number: '03',
    title: 'Al-Imran',
    info: 'Family of Imran',
    arabic: 'آل عمران',
    count: '200 verses',
  },
  {
    number: '04',
    title: 'An-Nisa',
    info: 'The Women',
    arabic: 'النساء',
    count: '176 verses',
  },
  {
    number: '05',
    title: 'Al-Maidah',
    info: 'The Table Spread',
    arabic: 'المائدة',
    count: '120 verses',
  },
  {
    number: '06',
    title: 'Al-Anam',
    info: 'The Cattle',
    arabic: 'الانام',
    count: '165 verses',
  },
  {
    number: '07',
    title: 'Al-Araf',
    info: 'The Heights',
    arabic: 'العراف',
    count: '206 verses',
  },
  {
    number: '08',
    title: 'Al-Anfal',
    info: 'The Spoils of War',
    arabic: 'الأنفال',
    count: '75 verses',
  },
  {
    number: '09',
    title: 'At-Taubah',
    info: 'The Repentance',
    arabic: 'التوبة',
    count: '129 verses',
  },
  {
    number: '10',
    title: 'Yunus',
    info: 'Jonah',
    arabic: 'يونس',
    count: '109 verses',
  },
  {
    number: '11',
    title: 'Hud',
    info: 'Hud',
    arabic: 'هود',
    count: '123 verses',
  },
  {
    number: '12',
    title: 'Yusuf',
    info: 'Joseph',
    arabic: 'يوسف',
    count: '111 verses',
  },
];
